name: CI

# Events that trigger workflow
on:
  # Runs on all pushes to branches
  push:
  # Runs on all PRs
  pull_request:
  # Runs every day at midnight UTC
  schedule:
    - cron: "0 0 * * *"
  # Manual Dispatch
  workflow_dispatch:

jobs:
  run-cace:
    runs-on: ubuntu-22.04
    name: Run CACE
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v3
      # Run CACE on the design
      - name: Setup Environment and Run CACE
        uses: efabless/cace-action@main
        with:
          pdk_family: 'sky130'
          open_pdks_rev: '4d5af10bfee4dab799566aaf903bb22aee69bac9'
          cace_rev: '4cad2ba2789973ebe99f27536004a3e50ea34814'
          cace_root: '.'
          cace_datasheet: 'cace/ota-5t.yaml'
          cace_source: 'schematic'
          cace_args: '--summary summary.md --sequential --parallel_parameters 1'
          token: ${{ secrets.GITHUB_TOKEN }}
      # Upload artifacts
      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: artifact
          path: |
            ${{ github.workspace }}/plots/
      # Add summary
      - name: Add Markdown to Step Summary
        run: cat summary.md >> $GITHUB_STEP_SUMMARY
